import type { IndustryEntry } from "./types";

/**
 * Industry landing pages (deck p10 + case studies + site testimonials).
 * Each entry pairs with content files in src/content/industries/<id>/.
 */
export const INDUSTRIES: readonly IndustryEntry[] = [
  {
    id: "healthcare",
    category: "industry",
    slugs: { en: "healthcare", id: "kesehatan" },
    title: { en: "Healthcare", id: "Kesehatan" },
    tagline: { en: "24/7 patient answers and bookings", id: "Jawab & booking pasien 24/7" },
    icon: "Stethoscope",
    nav: { megaMenu: true, order: 1 },
  },
  {
    id: "retail",
    category: "industry",
    slugs: { en: "retail-ecommerce", id: "ritel" },
    title: { en: "Retail & E-Commerce", id: "Ritel & E-Commerce" },
    tagline: { en: "Sell and support on every channel", id: "Jualan & layani di semua channel" },
    icon: "ShoppingBag",
    nav: { megaMenu: true, order: 2 },
  },
  {
    id: "fnb",
    category: "industry",
    slugs: { en: "food-beverage", id: "fnb" },
    title: { en: "Food & Beverage", id: "F&B" },
    tagline: { en: "Reservations and orders, handled 24/7", id: "Reservasi & order tertangani 24/7" },
    icon: "UtensilsCrossed",
    nav: { megaMenu: true, order: 3 },
  },
  {
    id: "education",
    category: "industry",
    slugs: { en: "education", id: "pendidikan" },
    title: { en: "Education", id: "Pendidikan" },
    tagline: { en: "Answer applicants around admission season", id: "Jawab calon siswa saat PMB" },
    icon: "GraduationCap",
    nav: { megaMenu: true, order: 4 },
  },
  {
    id: "finance",
    category: "industry",
    slugs: { en: "financial-services", id: "keuangan" },
    title: { en: "Financial Services", id: "Keuangan" },
    tagline: { en: "Compliant service at high volume", id: "Layanan compliant, volume tinggi" },
    icon: "Landmark",
    nav: { megaMenu: true, order: 5 },
  },
  {
    id: "government",
    category: "industry",
    slugs: { en: "government", id: "pemerintahan" },
    title: { en: "Government", id: "Pemerintahan" },
    tagline: { en: "Answer citizens, track every case", id: "Jawab warga, lacak tiap kasus" },
    icon: "Building2",
    nav: { megaMenu: true, order: 6 },
  },
  {
    id: "property",
    category: "industry",
    slugs: { en: "property", id: "properti" },
    title: { en: "Property", id: "Properti" },
    tagline: { en: "Qualify leads and book visits", id: "Kualifikasi leads & atur kunjungan" },
    icon: "Building",
    nav: { megaMenu: true, order: 7 },
  },
  {
    id: "beauty-wellness",
    category: "industry",
    slugs: { en: "beauty-wellness", id: "salon-kecantikan" },
    title: { en: "Beauty & Wellness", id: "Salon & Kecantikan" },
    tagline: { en: "Bookings, reminders, fewer no-shows", id: "Booking, reminder, minim no-show" },
    icon: "Sparkles",
    nav: { megaMenu: true, order: 8 },
  },
  {
    id: "hospitality",
    category: "industry",
    slugs: { en: "hospitality", id: "perhotelan" },
    title: { en: "Hospitality", id: "Perhotelan" },
    tagline: { en: "Reservations and guest questions, 24/7", id: "Reservasi & pertanyaan tamu, 24/7" },
    icon: "Hotel",
    nav: { megaMenu: true, order: 9 },
  },
  {
    id: "travel",
    category: "industry",
    slugs: { en: "tour-travel", id: "travel" },
    title: { en: "Tour & Travel", id: "Tour & Travel" },
    tagline: { en: "Multilingual answers across time zones", id: "Jawaban multi-bahasa lintas zona" },
    icon: "Plane",
    nav: { megaMenu: true, order: 10 },
  },
  {
    id: "nonprofit",
    category: "industry",
    slugs: { en: "nonprofit", id: "lembaga-sosial" },
    title: { en: "Nonprofit", id: "Lembaga Sosial" },
    tagline: { en: "Answer donors, run campaigns", id: "Jawab donatur & jalankan campaign" },
    icon: "HandHeart",
    nav: { megaMenu: true, order: 11 },
  },

  // ── Expansion wave (orders 12+). Only logistics is curated into the mega
  // menu; the rest are reachable from the /industri hub and internal links.
  {
    id: "logistics",
    category: "industry",
    slugs: { en: "logistics", id: "logistik" },
    title: { en: "Logistics", id: "Logistik" },
    tagline: { en: "Shipment updates and CS, 24/7", id: "Update kiriman & CS 24/7" },
    icon: "Truck",
    nav: { megaMenu: true, order: 12 },
  },
  {
    id: "fmcg",
    category: "industry",
    slugs: { en: "fmcg", id: "fmcg" },
    title: { en: "FMCG", id: "FMCG" },
    tagline: { en: "Serve distributors and consumers", id: "Layani distributor & konsumen" },
    icon: "ShoppingBasket",
    nav: { order: 13 },
  },
  {
    id: "isp",
    category: "industry",
    slugs: { en: "internet-service-providers", id: "isp" },
    title: { en: "Internet Service Providers", id: "Internet Service Provider" },
    tagline: { en: "Outage and billing support, 24/7", id: "Tangani gangguan & tagihan 24/7" },
    icon: "Wifi",
    nav: { order: 14 },
  },
  {
    id: "airlines",
    category: "industry",
    slugs: { en: "airlines", id: "maskapai" },
    title: { en: "Airlines", id: "Maskapai" },
    tagline: { en: "Answer passengers across time zones", id: "Jawab penumpang lintas zona waktu" },
    icon: "PlaneTakeoff",
    nav: { order: 15 },
  },
  {
    id: "entertainment",
    category: "industry",
    slugs: { en: "entertainment", id: "hiburan" },
    title: { en: "Entertainment", id: "Hiburan" },
    tagline: { en: "Tickets and events, no chat queue", id: "Tiket & event tanpa antrean chat" },
    icon: "Clapperboard",
    nav: { order: 16 },
  },
  {
    id: "gym-sports",
    category: "industry",
    slugs: { en: "fitness-sports", id: "gym-olahraga" },
    title: { en: "Fitness & Sports", id: "Gym & Padel" },
    tagline: { en: "Class bookings and memberships", id: "Booking kelas & membership otomatis" },
    icon: "Dumbbell",
    nav: { order: 17 },
  },
  {
    id: "saas",
    category: "industry",
    slugs: { en: "saas", id: "saas" },
    title: { en: "SaaS", id: "SaaS" },
    tagline: { en: "User onboarding and support, 24/7", id: "Onboarding & support pengguna 24/7" },
    icon: "Cloud",
    nav: { order: 18 },
  },
  {
    id: "transport",
    category: "industry",
    slugs: { en: "transport-services", id: "transportasi" },
    title: { en: "Transport Services", id: "Transportasi" },
    tagline: { en: "Schedules, fares, and orders in chat", id: "Jadwal, tarif, & pesanan di chat" },
    icon: "Bus",
    nav: { order: 19 },
  },
  {
    id: "automotive",
    category: "industry",
    slugs: { en: "automotive", id: "otomotif" },
    title: { en: "Automotive", id: "Otomotif" },
    tagline: { en: "Test-drive leads and service bookings", id: "Leads test drive & booking servis" },
    icon: "Car",
    nav: { order: 20 },
  },
  {
    id: "tech-startup",
    category: "industry",
    slugs: { en: "technology-startups", id: "teknologi-startup" },
    title: { en: "Technology & Startups", id: "Teknologi & Startup" },
    tagline: { en: "Scale support without headcount", id: "Scale support tanpa nambah tim" },
    icon: "Rocket",
    nav: { order: 21 },
  },
  {
    id: "outsourcing",
    category: "industry",
    slugs: { en: "outsourcing", id: "outsourcing" },
    title: { en: "Outsourcing & BPO", id: "Outsourcing" },
    tagline: { en: "One inbox for every client", id: "Satu inbox untuk banyak klien" },
    icon: "Headphones",
    nav: { order: 22 },
  },
  {
    id: "professional-services",
    category: "industry",
    slugs: { en: "professional-services", id: "jasa-profesional" },
    title: { en: "Professional Services", id: "Jasa Profesional" },
    tagline: { en: "Consultations and appointments, scheduled", id: "Konsultasi & janji temu terjadwal" },
    icon: "Briefcase",
    nav: { order: 23 },
  },

  // Health sub-verticals; /industri/kesehatan stays the umbrella page.
  {
    id: "clinics",
    category: "industry",
    slugs: { en: "clinics", id: "klinik" },
    title: { en: "Clinics", id: "Klinik" },
    tagline: { en: "Patient bookings and reminders", id: "Booking pasien & reminder otomatis" },
    icon: "HeartPulse",
    nav: { order: 24 },
  },
  {
    id: "dental",
    category: "industry",
    slugs: { en: "dental-clinics", id: "dental" },
    title: { en: "Dental Clinics", id: "Klinik Gigi" },
    tagline: { en: "Appointments and patient recalls", id: "Janji temu & recall pasien jalan" },
    icon: "Smile",
    nav: { order: 25 },
  },
  {
    id: "barbershop",
    category: "industry",
    slugs: { en: "barbershops", id: "barbershop" },
    title: { en: "Barbershops", id: "Barbershop" },
    tagline: { en: "Chair bookings without manual replies", id: "Booking kursi tanpa balas manual" },
    icon: "Scissors",
    nav: { order: 26 },
  },
  {
    id: "pharmacy",
    category: "industry",
    slugs: { en: "pharmacies", id: "apotek" },
    title: { en: "Pharmacies", id: "Apotek" },
    tagline: { en: "Stock checks and refills via chat", id: "Cek stok & tebus resep via chat" },
    icon: "Pill",
    nav: { order: 27 },
  },

  // Education sub-verticals; /industri/pendidikan stays the umbrella page.
  {
    id: "schools",
    category: "industry",
    slugs: { en: "schools", id: "sekolah" },
    title: { en: "Schools", id: "Sekolah" },
    tagline: { en: "Admissions answered 24/7", id: "PSB & info sekolah terjawab 24/7" },
    icon: "School",
    nav: { order: 28 },
  },
  {
    id: "edutech",
    category: "industry",
    slugs: { en: "edtech", id: "edutech" },
    title: { en: "EdTech", id: "Edutech" },
    tagline: { en: "Activate and retain learners", id: "Onboarding & retensi pelajar" },
    icon: "Laptop",
    nav: { order: 29 },
  },
] as const;
